/*Steven Lantz
*ITDEV-140-002
*Fall 2019
*Semester Project: Airline App*/
package lantz_airlineapp;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import java.util.ArrayList;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class AirlineUX extends javax.swing.JFrame {

//Instantiating objects
    Date date = new Date();//Used to determine of user entered correct date format
    Passenger flyer; //Hold all passenger data
    Fares fares = new Fares();//Firstclass price, economy price, discount for under 12
    Random rand = new Random();//Random number generator
    CRUD crud;//Database operations
    Destinations dest = new Destinations();//Destination names and prices
   

//Fields
    private ArrayList<Passenger>tickets = new ArrayList<>();//Holder passenger objects for multiple number of tickets
    int bagWeight;//Once bagWeight matches criteria, will be assigned
   String phoneNumber;//Once phoneNumber matches criteria, will be assigned
   private int totalDue; //Assigned value of total of all tickets


//Accessor for jtable
public JTable getJTable() {
        return jTable1;
    }

//Set crud
    public void setCrud(CRUD crud) {
        this.crud = crud;
    }

//Accessor 
public int getTotalDue(){
    return totalDue ;
}    

    /**
     * Creates new form AirlineUX
     */
    //Set all error text to false
    public AirlineUX() {
         
        initComponents();
        
         BuildTable build = new BuildTable();
        
        
        getContentPane().setBackground(Color.DARK_GRAY);
        
        lblErrorFName.setVisible(false);
        lblErrorLName.setVisible(false);
        lblErrorPhone.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorBag.setVisible(false);
        lblErrorDepart.setVisible(false);
        lblErrorUnder12.setVisible(false);
        lblErrorArrival.setVisible(false);
        lblErrorDestination.setVisible(false);
        lblErrorFirstEcon.setVisible(false);
        btnCheckOut.setVisible(false);
     
    }//End of Airline UX
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDepart = new javax.swing.JFormattedTextField();
        txtArrival = new javax.swing.JFormattedTextField();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtBagWeight = new javax.swing.JTextField();
        radFirstClass = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblErrorFName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblErrorLName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        lblErrorPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbDestination = new javax.swing.JComboBox<>();
        radEconomy = new javax.swing.JRadioButton();
        radUnder12No = new javax.swing.JRadioButton();
        radUnder12Yes = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorBag = new javax.swing.JLabel();
        lblErrorUnder12 = new javax.swing.JLabel();
        lblErrorDestination = new javax.swing.JLabel();
        lblErrorFirstEcon = new javax.swing.JLabel();
        lblErrorDepart = new javax.swing.JLabel();
        lblErrorArrival = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniInfo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airline UX");
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Cheap-O Airlines");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broken_plane2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel4.setText("Passenger Information");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Departure Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel12.setText("Arrival Date");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 30));

        txtDepart.setToolTipText("Please enter date as: mm/dd/yyyy");
        jPanel2.add(txtDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 92, -1));

        txtArrival.setToolTipText("Please enter date as: mm/dd/yyyy");
        jPanel2.add(txtArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 84, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setText("Clear ");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("Hawaii");

        jLabel20.setText("$300");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setText("First Class");

        jLabel25.setText("$300");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setText("Economy");

        jLabel26.setText("$150");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setText("Colorado");

        jLabel22.setText("$150");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setAutoscrolls(true);
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setNextFocusableComponent(this);

        jLabel15.setText("California");

        jLabel16.setText("$200");

        jLabel6.setText("California");

        jLabel28.setText("$200");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel28))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setText("Florida ");

        jLabel18.setText("$100");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(1, 1, 1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel10.setText("Travel Dates");

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Phone:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, -1));
        jPanel12.add(txtBagWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 160, -1));

        radFirstClass.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup1.add(radFirstClass);
        radFirstClass.setText("First Class");
        jPanel12.add(radFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel3.setText("First Name:");
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));
        jPanel12.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 160, -1));

        jLabel5.setText("Last Name:");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        lblErrorFName.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorFName.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorFName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorFName.setText("Please enter a first name");
        lblErrorFName.setToolTipText("");
        jPanel12.add(lblErrorFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 145, 19));

        txtPhone.setToolTipText("Must be in xxx-xxx-xxxx format");
        jPanel12.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, -1));

        jLabel7.setText("Email:");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 18));

        lblErrorLName.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorLName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorLName.setText("Please enter a last name");
        jPanel12.add(lblErrorLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 149, -1));
        jPanel12.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        lblErrorPhone.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorPhone.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPhone.setText("Please enter a phone number");
        jPanel12.add(lblErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 182, -1));

        jLabel8.setText("Bag Weight:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel9.setText("Destination");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 91, -1));

        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "Colorado", "Florida", "Hawaii" }));
        cmbDestination.setSelectedIndex(-1);
        jPanel12.add(cmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 96, 30));

        radEconomy.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup1.add(radEconomy);
        radEconomy.setText("Economy");
        jPanel12.add(radEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        radUnder12No.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup2.add(radUnder12No);
        radUnder12No.setText("No");
        jPanel12.add(radUnder12No, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        radUnder12Yes.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup2.add(radUnder12Yes);
        radUnder12Yes.setText("Yes");
        jPanel12.add(radUnder12Yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel13.setText("Passenger under 12?");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 128, -1));
        jPanel12.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, 20));

        lblErrorEmail.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorEmail.setText("Please enter an email");
        jPanel12.add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        lblErrorBag.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblErrorBag.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorBag.setText("Please enter a bag weight");
        jPanel12.add(lblErrorBag, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lblErrorUnder12.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorUnder12.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorUnder12.setText("Please choose Yes or No");
        jPanel12.add(lblErrorUnder12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        lblErrorDestination.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorDestination.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDestination.setText("Please choose a destination");
        jPanel12.add(lblErrorDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        lblErrorFirstEcon.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorFirstEcon.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorFirstEcon.setText("Please  make a selection");
        jPanel12.add(lblErrorFirstEcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lblErrorDepart.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorDepart.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDepart.setText("Please enter a departure date");

        lblErrorArrival.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblErrorArrival.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorArrival.setText("Please enter a return date");

        jLabel14.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel14.setText("Destinations and Prices");

        btnCheckOut.setText("Check Out");
        btnCheckOut.setToolTipText("");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        mniInfo.setText("Info");
        mniInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInfoActionPerformed(evt);
            }
        });
        jMenu1.add(mniInfo);
        jMenu1.add(jSeparator1);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        jMenu1.add(mniExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(lblErrorDepart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorArrival))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel10)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorDepart)
                    .addComponent(lblErrorArrival))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Exit chosen from file menu
    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
       int selectedOption = JOptionPane.showConfirmDialog(null," Are you sure you want to quit?");
       
       if(selectedOption == JOptionPane.YES_NO_OPTION)
           this.dispose();
    }//GEN-LAST:event_mniExitActionPerformed

//Info chosen from file menu
    private void mniInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInfoActionPerformed
          JOptionPane.showMessageDialog(null,"Steven Lantz"
                                                                                + "\nITDEV-140-002"
                                                                                +  "\nFall 2019"
                                                                                + "\nFinal Project: Airline Booking" 
                                                                                +  "\n" + date.toLocaleString() );
    }//GEN-LAST:event_mniInfoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
//Will not build a passenger object and send to database if all criteria are not met

//Test if forms are empty or meet criteria
if (txtFName.getText().isEmpty() || txtLName.getText().isEmpty() || txtPhone.getText().isEmpty()
                || txtEmail.getText().isEmpty() || txtBagWeight.getText().isEmpty()
                || (radEconomy.isSelected() == false && radFirstClass.isSelected() == false)
                || (radUnder12Yes.isSelected() == false && radUnder12No.isSelected() == false)
                || cmbDestination.getSelectedIndex() == -1   || txtDepart.getText().isEmpty()
                || txtArrival.getText().isEmpty() || isInteger(txtBagWeight.getText())== false
                || bagWeight > 50
                || (isValidDate(txtDepart.getText(), "mm/dd/yyyy") == false) 
                || (isValidDate(txtArrival.getText(), "mm/dd/yyyy") == false)
                || checkPhoneNumber(txtPhone.getText()) == false)
{

//If field is empty, display error message
            if (txtFName.getText().isEmpty()) {
                lblErrorFName.setVisible(true);
            }
            if (txtLName.getText().isEmpty()) {
                lblErrorLName.setVisible(true);
            }
            if (txtPhone.getText().isEmpty()) {
                lblErrorPhone.setVisible(true);
            }
            if (txtEmail.getText().isEmpty()) {
                lblErrorEmail.setVisible(true);
            }
            if (txtBagWeight.getText().isEmpty()) {
                lblErrorBag.setVisible(true);
            }
            if (txtDepart.getText().isEmpty()) {
                lblErrorDepart.setVisible(true);
            }
            if (txtArrival.getText().isEmpty()) {
                lblErrorArrival.setVisible(true);
            }
            if (cmbDestination.getSelectedIndex() == -1) {
                lblErrorDestination.setVisible(true);
            }
            if (radUnder12Yes.isSelected() == false && radUnder12No.isSelected() == false) {
                lblErrorUnder12.setVisible(true);
            }
            if (radEconomy.isSelected() == false && radFirstClass.isSelected() == false) {
                lblErrorFirstEcon.setVisible(true);
            }
//Test bag weight for limit and maximum value
       if(isInteger(txtBagWeight.getText()) == false) {
           JOptionPane.showMessageDialog(null, "Please enter a valid number");
       }
if(bagWeight > 50){
            JOptionPane.showMessageDialog(null, "Bag Weight must be 50 pounds or less.");
        }

//Test if dates are in valid format
            if (isValidDate(txtDepart.getText(), "mm/dd/yyyy") == false) {
                JOptionPane.showMessageDialog(null, "Please enter departure date as: mm/dd/yyyy");
            }
               if (isValidDate(txtArrival.getText(), "mm/dd/yyyy") == false) {
                JOptionPane.showMessageDialog(null, "Please enter arrival date as: mm/dd/yyyy");
            }

//Check if phone number is in valid format
               if(checkPhoneNumber(txtPhone.getText()) == false){
                   JOptionPane.showMessageDialog(null, "Please enter phone number in xxx-xxx-xxxx format");
               }
        }//End of if tests

//If all fields are filled out correctly
else
{

//Create object from fields in form
    buildPassengerObject();

//Insert passenger object into DB 
    crud.insertDB(flyer);

//Add passenger object to tickets array list
    tickets.add(flyer);

//Show the updated database
    crud.showTable();

    clearForm();
    
    btnCheckOut.setVisible(true);
    findTotalDue();
  
    }//GEN-LAST:event_btnSubmitActionPerformed
}

//Clears all fields in the form
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

//Clear all fields in form
    public void clearForm(){
//Set all fields to blank
        txtFName.setText("");
        txtLName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtBagWeight.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        cmbDestination.setSelectedIndex(-1);
        txtDepart.setText("");
        txtArrival.setText("");
//Hide error messages
        lblErrorFName.setVisible(false);
        lblErrorLName.setVisible(false);
        lblErrorPhone.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorBag.setVisible(false);
        lblErrorDepart.setVisible(false);
        lblErrorUnder12.setVisible(false);
        lblErrorArrival.setVisible(false);
        lblErrorDestination.setVisible(false);
        lblErrorFirstEcon.setVisible(false);
}
    
    
    
  //Used this for testing purposes
  //Build the table with no database entries
    /**/
//Checkout button pressed
    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        this.dispose();
        new Payment(totalDue).setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

   
//Take input from GUI form and build a passenger object
    public void buildPassengerObject() {
        flyer = new Passenger();

//Get text from GUI forms
            flyer.setfName(txtFName.getText());
            flyer.setlName(txtLName.getText());
            flyer.setPhoneNumber(phoneNumber);
            flyer.setEmail(txtEmail.getText());
            flyer.setBagWeight(bagWeight);
            
            if (radUnder12Yes.isSelected()) {
                flyer.setUnder12(true);
            }
            if (radUnder12No.isSelected()) {
                flyer.setUnder12(false);
            }
            
            flyer.setDestination(cmbDestination.getSelectedItem().toString());
            flyer.setDepartDate(txtDepart.getText());
            flyer.setReturnDate(txtArrival.getText());
            
            if (radFirstClass.isSelected()) {
                flyer.setFarePrice(fares.getFIRST_CLASS_PRICE());
            }
            if (radEconomy.isSelected()) {
                flyer.setFarePrice(fares.getECONOMY_CLASS_PRICE());
            }
            flyer.setDestination(cmbDestination.getSelectedItem().toString());
            flyer.setPassengerNumber(flyerNumber());//flyerNumber method returns a randomly generated number
            
            if(cmbDestination.getSelectedItem().equals("California")){
                flyer.setDestinationPrice(dest.getCALIFORNIA());
            }
            if(cmbDestination.getSelectedItem().equals("Florida")){
                flyer.setDestinationPrice(dest.getFLORIDA());
            }
            if(cmbDestination.getSelectedItem().equals("Colorado")){
                flyer.setDestinationPrice(dest.getCOLORADO());
            }
            if(cmbDestination.getSelectedItem().equals("Hawaii")){
                flyer.setDestinationPrice(dest.getHAWAII());
            }
           /*totalFair method returns destination price 
           + fare price(economy or first class) 
           + discount if under 12*/
            flyer.setTotalFare(totalFair());
    
    }//End of buildPassengerObject
    

  /*totalFair method returns destination price 
   *       + fare price(economy or first class) 
   *     + discount if under 12
   *Returns int*/
    public int totalFair(){
       int fare = 0;
       int destinationPrice = 0;
        if(flyer.isUnder12() == true){
          fare += fares.getUNDER_12_PRICE() +flyer.getFarePrice()+ flyer.getDestinationPrice();
       }
       if(flyer.isUnder12() == false){
           fare += flyer.getFarePrice() + flyer.getDestinationPrice();
       }
       return fare;
    }

//Test to see if date user inputs in valid format
//Pass in date to you want to check as well as format your are checking for
    public static boolean isValidDate(String date, String dateFormat) {

        if (date == null) {
            return false;
        }
        if (dateFormat == null) {
            return false;
        }
        SimpleDateFormat format = new SimpleDateFormat(dateFormat);
        format.setLenient(false);

        try {
            format.parse(date.trim());
        } catch (ParseException pe) {
            
            pe.printStackTrace();
            return false;
        }
        return true;
    }
    
   //Test to see if integer
    //Assigns text field value to variable bagWeight if integer
    public boolean isInteger(String userInput) {
        try {
            Integer.parseInt(userInput);
        } catch (NumberFormatException e) {

            return false;
        } catch (NullPointerException e) {

            return false;
        }
        bagWeight = Integer.parseInt(userInput);
        return true;
    }
    
//Test if phone number is in right format
//Returns true/false
//Assigns variable 'phoneNumber' if it matches criteria
    public boolean checkPhoneNumber(String phoneNumber){
        
        Pattern pattern = Pattern.compile("\\d{3}-\\d{3}-\\d{4}");
        Matcher matcher = pattern.matcher(phoneNumber);
        
        if(matcher.matches()){
            
            this.phoneNumber = phoneNumber;
            return true;
        }
        else 
            return false;
    }
     public int findTotalDue(){
        totalDue = 0;
         for (int i = 0; i < tickets.size(); i++) {
             this.totalDue += tickets.get(i).getTotalFare();
         }
         return totalDue;
     }

//Create random number for passenger number
    public int flyerNumber(){
      int flyerNumber = rand.nextInt(100000) + 10000;
      
      return flyerNumber;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineUX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineUX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineUX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineUX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineUX().setVisible(true);
            }
        });
    }


       
    
    
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbDestination;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrorArrival;
    private javax.swing.JLabel lblErrorBag;
    private javax.swing.JLabel lblErrorDepart;
    private javax.swing.JLabel lblErrorDestination;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFName;
    private javax.swing.JLabel lblErrorFirstEcon;
    private javax.swing.JLabel lblErrorLName;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblErrorUnder12;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniInfo;
    private javax.swing.JRadioButton radEconomy;
    private javax.swing.JRadioButton radFirstClass;
    private javax.swing.JRadioButton radUnder12No;
    private javax.swing.JRadioButton radUnder12Yes;
    private javax.swing.JFormattedTextField txtArrival;
    private javax.swing.JTextField txtBagWeight;
    private javax.swing.JFormattedTextField txtDepart;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
